# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import interpreter_pb2 as interpreter__pb2


class IntepreterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Interpret = channel.unary_stream(
        '/Intepreter/Interpret',
        request_serializer=interpreter__pb2.Call.SerializeToString,
        response_deserializer=interpreter__pb2.Output.FromString,
        )


class IntepreterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Interpret(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IntepreterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Interpret': grpc.unary_stream_rpc_method_handler(
          servicer.Interpret,
          request_deserializer=interpreter__pb2.Call.FromString,
          response_serializer=interpreter__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Intepreter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
